version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    groups:
      composer-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
