<?php

declare(strict_types=1);

use Lotgd\Page\Header;
use Lotgd\Translator;

Translator::getInstance()->setSchema('faq');
Header::popupHeader("General Questions with Spoilers");
$c = Translator::translateInline("Return to Contents");
$output->rawOutput("<a href='petition.php?op=faq'>$c</a><hr>");
$output->output("`n`n`&(Warning, the FAQs below might contain some spoilers, so if you really want to discover things on your own, you'd be better off not reading too far.");
$output->output("This is not a manual.  It's a self-help pamphlet.)`n`n`n`n`n`n`n`n`n`n`n`n`n");
$output->output("`^1. What are gems for?`n");
$output->output("`@Gems are magical portals into the future. Gaze into the depths of a gem and you can see that which is to come.`n");
$output->output("Gullible? We sure hope not!`n");
$output->output("Lots of people love those little gemstones and are willing to trade things for them.");
$output->output("Your local bartender is something of a gemologist.`n`n");
$output->output("`^2. How do you get gems?`n");
$output->output("`@To the mines with you!!`n");
$output->output("Actually, you can't mine them.  (Well, you can, but only if you get lucky and find the mine. Warning though, mines can be dangerous.)");
$output->output("Gems can be found in the forest during 'special events' that happen randomly - if you play often enough, you're bound to stumble across one at some point.");
$output->output("Gems can also be gained very occasionally from a forest fight.`n`n");
$output->output("`^3. Why do some people seem to have so many hitpoints at a low level?`n");
$output->output("`@Cause they're bigger than you.`n");
$output->output("No, really, they *are* bigger than you. You'll be big too someday.`n`n");
$output->output("`^4. Does that have something to do with the titles that people have?`n");
$output->output("`@But of course!`n");
$output->output("Indeed, every time you kill the dragon, you return to level one.");
$output->output("If you kill the dragon enough times, you get a new title.");
$output->output("So low level players with titles have had opportunities to embiggen themselves. (see Hall of Fame)`n`n");
$output->output("`^5. What's a buff?`n");
$output->output("`@It's what we use to shine our shoes.`n");
$output->output("Did you think it was some sort of temporary or permanent effect which affects your stats in a positive or negative manner? Hah!`n`n");
$output->output("`^6. Why does that old man keep hitting me with an ugly/pretty stick in the forest?`n");
$output->output("`@You look like a pi&ntilde;ata!`n", true);
$output->output("It's a special event that can add or remove charm.`n`n");
$output->output("`^7. Well, what's the point of charm?`n");
$output->output("`@To get chicks (or guys).`n");
$output->output("Well, actually, that *is* the point.");
$output->output("Visit some folks at the Inn, and you ought to be able to figure this one out.");
$output->output("The more charm you have, the more successful you'll be at wooing said folks.`n`n");
$output->output("`^8. Okay, I saw the man in the forest and he hit me with his ugly stick, but it says I'm uglier than the stick, and I made it lose a charm point. What's going on?`n");
$output->output("`@You're clearly the least charming person on the planet.");
$output->output("And if you're the person who actually *asked* this question, you're also the dumbest.");
$output->output("Use a little power of inference, wouldja?");
$output->output("No. Really.`n");
$output->output("Okay, we did say you were the dumbest, so: it means you currently have zero charm points.`n`n");
$output->output("`^9. How do I check my charm?`n");
$output->output("`@Take a peek in the mirror once in a while.`n");
$output->output("We jest - there's no mirror.");
$output->output("You'll have to ask a friend how you look today - the responses may be vague, but they'll give you a clue how you're doing.`n`n");
$output->output("`^10. Who is the Management?`n");
$output->output("`@Appleshiner, Foilwench and Catscradler are in charge of this FAQ, but if something goes wrong, blame MightyE or Kendaer.");
$output->output("They're in charge of everything else.");
$output->output("To get ahold of them, or one of their trusty helpers, use the Petition for Help link.`n`n");
$output->output("`^11. How did they get to be so darn attractive, anyway?`n");
$output->output("`@Lots of at-home facials, my dear!!");
$output->output("MightyE especially enjoys the Grapefruit Essence Facial Masque.`n");
$output->rawOutput("<hr><a href='petition.php?op=faq'>$c</a>");
