<?php

declare(strict_types=1);

namespace Lotgd\Upgrade;

/**
 * The files an installation cannot run without, and which of them are missing.
 *
 * On shared hosting the game arrives by FTP, a few thousand files at a time,
 * and a transfer that silently skipped one breaks the game in ways that are
 * hard to trace back to it. Composer's own records cannot answer the question:
 * vendor/ is not classmap-optimized, and nothing lists the game's own code. So
 * the game ships the list itself, in shipped-files.txt next to this class.
 *
 * The list holds only what every installation needs. Modules, themes and
 * images are left out on purpose: administrators remove the ones they do not
 * use, and a check that calls that an incomplete upload would be wrong. The
 * installer is left out because it is deleted once the game is installed.
 *
 * A workflow regenerates the list on every push to master
 * (.github/workflows/shipped-files.yml), so it is never edited by hand.
 *
 * installer.php loads this file directly, before the Composer autoloader,
 * because a missing vendor/ file is exactly what would stop the autoloader
 * before anything could be reported. It therefore depends on nothing else.
 */
final class ShippedFiles
{
    /** Directories whose every file is required. */
    public const REQUIRED_DIRECTORIES = ['async/', 'lib/', 'migrations/', 'pages/', 'src/', 'vendor/'];

    /** Files at the top level that are required although they are not PHP. */
    public const REQUIRED_TOP_LEVEL_FILES = ['.htaccess'];

    /** Top-level PHP files that are not required. */
    public const OPTIONAL_TOP_LEVEL_FILES = ['installer.php'];

    public const LIST_FILE = __DIR__ . '/shipped-files.txt';

    /** The list does not list itself: it describes the others. */
    private const LIST_PATH = 'src/Lotgd/Upgrade/shipped-files.txt';

    /**
     * Whether a path, relative to the game directory with forward slashes,
     * belongs to the required set.
     */
    public static function isRequired(string $path): bool
    {
        if ($path === self::LIST_PATH) {
            return false;
        }
        if (!str_contains($path, '/')) {
            if (in_array($path, self::REQUIRED_TOP_LEVEL_FILES, true)) {
                return true;
            }

            return str_ends_with($path, '.php') && !in_array($path, self::OPTIONAL_TOP_LEVEL_FILES, true);
        }
        foreach (self::REQUIRED_DIRECTORIES as $directory) {
            if (str_starts_with($path, $directory)) {
                return true;
            }
        }

        return false;
    }

    /**
     * The required subset of a listing such as `git ls-files`, sorted.
     *
     * @param iterable<string> $paths
     *
     * @return list<string>
     */
    public static function fromListing(iterable $paths): array
    {
        $required = [];
        foreach ($paths as $path) {
            $path = trim(str_replace('\\', '/', (string) $path));
            if ($path !== '' && self::isRequired($path)) {
                $required[] = $path;
            }
        }
        $required = array_values(array_unique($required));
        sort($required, SORT_STRING);

        return $required;
    }

    /**
     * The contents of the list file for a set of required paths.
     *
     * @param list<string> $required
     */
    public static function render(array $required): string
    {
        return "# Files every installation needs, one per line, relative to the game directory.\n"
            . "# Generated by scripts/build-shipped-files.php on every push to master; do not edit.\n"
            . implode("\n", $required) . "\n";
    }

    /**
     * The paths a list file names.
     *
     * @return list<string>|null Null when the list cannot be read
     */
    public static function read(string $listFile = self::LIST_FILE): ?array
    {
        if (!is_file($listFile) || !is_readable($listFile)) {
            return null;
        }
        $lines = file($listFile, FILE_IGNORE_NEW_LINES);
        if ($lines === false) {
            return null;
        }

        $paths = [];
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line !== '' && $line[0] !== '#') {
                $paths[] = $line;
            }
        }

        return $paths;
    }

    /**
     * Required files that are not present under $root.
     *
     * @return list<string>|null Missing paths, or null when the list itself is
     *                           missing and nothing can be said
     */
    public static function missing(string $root, string $listFile = self::LIST_FILE): ?array
    {
        $paths = self::read($listFile);
        if ($paths === null) {
            return null;
        }

        $root = rtrim($root, '/\\');
        $missing = [];
        foreach ($paths as $path) {
            if (!is_file($root . '/' . $path)) {
                $missing[] = $path;
            }
        }

        return $missing;
    }

    /**
     * Whether this installation can be incomplete in the first place.
     *
     * A container runs a complete image and sets LOTGD_STATE_PATH. Checking it
     * could only produce a false report: an image built from the commit before
     * the list was regenerated still names a file that commit removed.
     */
    public static function applies(): bool
    {
        $statePath = getenv('LOTGD_STATE_PATH');

        return $statePath === false || trim($statePath) === '';
    }

    /**
     * A short description of missing files for a message.
     *
     * @param list<string> $missing
     *
     * @return string Plain text; escape it for HTML
     */
    public static function summarize(array $missing, int $show = 10): string
    {
        $shown = array_slice($missing, 0, $show);
        $text = implode(', ', $shown);
        $rest = count($missing) - count($shown);
        if ($rest > 0) {
            $text .= sprintf(' and %d more', $rest);
        }

        return $text;
    }
}
