<?php

declare(strict_types=1);

namespace Lotgd\Upgrade;

/**
 * The files an installation cannot run without, and which of them are missing.
 *
 * On shared hosting the game arrives by FTP, a few thousand files at a time,
 * and a transfer that silently skipped one breaks the game in ways that are
 * hard to trace back to it. Composer's own records cannot answer the question:
 * vendor/ is not classmap-optimized, and nothing lists the game's own code. So
 * the game ships the list itself, in shipped-files.txt next to this class.
 *
 * The list holds only what every installation needs. Modules, themes and
 * images are left out on purpose: administrators remove the ones they do not
 * use, and a check that calls that an incomplete upload would be wrong. The
 * installer's own files are listed but checked only by the installer, since
 * they may be deleted once the game is installed.
 *
 * The list names the game version it was made for. During an FTP update the
 * new common.php usually arrives long before src/ and migrations/; until the
 * list for the new version has arrived too, the old one would describe the old
 * file set and call an incomplete upload complete. So a list for another
 * version counts as missing, and so does a missing list.
 *
 * A workflow regenerates the list on every push to master
 * (.github/workflows/shipped-files.yml), so it is never edited by hand.
 *
 * installer.php loads this file directly, before the Composer autoloader,
 * because a missing vendor/ file is exactly what would stop the autoloader
 * before anything could be reported. It therefore depends on nothing else.
 */
final class ShippedFiles
{
    /** Directories whose every file is required. */
    public const REQUIRED_DIRECTORIES = ['async/', 'lib/', 'migrations/', 'pages/', 'src/', 'vendor/'];

    /** Files at the top level that are required although they are not PHP. */
    public const REQUIRED_TOP_LEVEL_FILES = ['.htaccess'];

    public const LIST_FILE = __DIR__ . '/shipped-files.txt';

    /** Where the list lives, relative to the game directory. */
    public const LIST_PATH = 'src/Lotgd/Upgrade/shipped-files.txt';

    private const VERSION_PREFIX = '# version: ';

    /**
     * Whether a path, relative to the game directory with forward slashes, is
     * needed by every installation.
     */
    public static function isRequired(string $path): bool
    {
        if ($path === self::LIST_PATH || self::isInstallerFile($path)) {
            return false;
        }
        if (!str_contains($path, '/')) {
            return in_array($path, self::REQUIRED_TOP_LEVEL_FILES, true) || str_ends_with($path, '.php');
        }
        foreach (self::REQUIRED_DIRECTORIES as $directory) {
            if (str_starts_with($path, $directory)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Whether a path belongs to the installer, which only the installer itself
     * needs and which may be deleted once the game is installed.
     */
    public static function isInstallerFile(string $path): bool
    {
        return $path === 'installer.php' || str_starts_with($path, 'install/');
    }

    /**
     * The listed subset of a listing such as `git ls-files`, sorted.
     *
     * @param iterable<string> $paths
     *
     * @return list<string>
     */
    public static function fromListing(iterable $paths): array
    {
        $listed = [];
        foreach ($paths as $path) {
            $path = trim(str_replace('\\', '/', (string) $path));
            if ($path !== '' && (self::isRequired($path) || self::isInstallerFile($path))) {
                $listed[] = $path;
            }
        }
        $listed = array_values(array_unique($listed));
        sort($listed, SORT_STRING);

        return $listed;
    }

    /**
     * The contents of the list file.
     *
     * @param list<string> $paths
     */
    public static function render(array $paths, string $version): string
    {
        return "# Files every installation needs, one per line, relative to the game directory.\n"
            . "# Generated by scripts/build-shipped-files.php on every push to master; do not edit.\n"
            . self::VERSION_PREFIX . $version . "\n"
            . implode("\n", $paths) . "\n";
    }

    /**
     * The version a list file was made for and the paths it names.
     *
     * @return array{version:string|null,paths:list<string>}|null Null when the list cannot be read
     */
    public static function read(string $listFile = self::LIST_FILE): ?array
    {
        if (!is_file($listFile) || !is_readable($listFile)) {
            return null;
        }
        $lines = file($listFile, FILE_IGNORE_NEW_LINES);
        if ($lines === false) {
            return null;
        }

        $version = null;
        $paths = [];
        foreach ($lines as $line) {
            $line = trim($line);
            if (str_starts_with($line, self::VERSION_PREFIX)) {
                $version = substr($line, strlen(self::VERSION_PREFIX));
            } elseif ($line !== '' && $line[0] !== '#') {
                $paths[] = $line;
            }
        }

        return ['version' => $version, 'paths' => $paths];
    }

    /**
     * The game version common.php declares, read without running it.
     */
    public static function versionOf(string $commonPhp): ?string
    {
        if (!is_file($commonPhp)) {
            return null;
        }
        $source = (string) file_get_contents($commonPhp);

        return preg_match('/^\$logd_version = "([^"]+)";$/m', $source, $match) === 1 ? $match[1] : null;
    }

    /**
     * Listed files that are not present under $root.
     *
     * @param string|null $codeVersion      The version the code on the server declares; null skips the
     *                                      comparison with the list's own version
     * @param bool        $includeInstaller Whether the installer's files are required too
     *
     * @return list<string> Missing paths. The list itself is reported when it is missing or was made
     *                      for another version, because then it cannot describe this upload.
     */
    public static function missing(
        string $root,
        ?string $codeVersion,
        bool $includeInstaller = false,
        string $listFile = self::LIST_FILE
    ): array {
        $list = self::read($listFile);
        if ($list === null || ($codeVersion !== null && $list['version'] !== $codeVersion)) {
            return [self::LIST_PATH];
        }

        $root = rtrim($root, '/\\');
        $missing = [];
        foreach ($list['paths'] as $path) {
            if (!$includeInstaller && self::isInstallerFile($path)) {
                continue;
            }
            if (!is_file($root . '/' . $path)) {
                $missing[] = $path;
            }
        }

        return $missing;
    }

    /**
     * Whether this installation can be incomplete in the first place.
     *
     * A container runs a complete image and sets LOTGD_STATE_PATH. Checking it
     * could only produce a false report: an image built from the commit before
     * the list was regenerated still names a file that commit removed.
     */
    public static function applies(): bool
    {
        $statePath = getenv('LOTGD_STATE_PATH');

        return $statePath === false || trim($statePath) === '';
    }

    /**
     * A short description of missing files for a message.
     *
     * @param list<string> $missing
     *
     * @return string Plain text; escape it for HTML
     */
    public static function summarize(array $missing, int $show = 10): string
    {
        $shown = array_slice($missing, 0, $show);
        $text = implode(', ', $shown);
        $rest = count($missing) - count($shown);
        if ($rest > 0) {
            $text .= sprintf(' and %d more', $rest);
        }

        return $text;
    }
}
